/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 */

@class NSString, NSDictionary, NSURL, NSArray, LSApplicationProxy;

@interface LSResourceProxy : NSObject  {
}

@property(readonly) NSString * localizedName;
@property(readonly) bool boundIconIsBadge;
@property(readonly) NSDictionary * iconsDictionary;

- (id)iconDataForVariant:(int)arg1;
- (id)iconsDictionary;
- (void)setLocalizedName:(id)arg1;
- (id)_initWithLocalizedName:(id)arg1;
- (id)boundDataContainerURL;
- (bool)boundIconIsBadge;
- (id)boundIconFileNames;
- (bool)boundIconIsPrerendered;
- (id)boundIconCacheKey;
- (id)iconStyleDomain;
- (id)boundContainerURL;
- (id)boundApplicationIdentifier;
- (id)boundResourcesDirectoryURL;
- (id)typeOwner;
- (id)boundIconsDictionary;
- (id)_initWithLocalizedName:(id)arg1 boundApplicationIdentifier:(id)arg2 boundContainerURL:(id)arg3 dataContainerURL:(id)arg4 boundResourcesDirectoryURL:(id)arg5 boundIconsDictionary:(id)arg6 boundIconCacheKey:(id)arg7 boundIconFileNames:(id)arg8 typeOwner:(id)arg9 boundIconIsPrerendered:(bool)arg10 boundIconIsBadge:(bool)arg11;
- (void)setBoundIconIsBadge:(bool)arg1;
- (void)setBoundIconIsPrerendered:(bool)arg1;
- (void)setTypeOwner:(id)arg1;
- (void)setBoundIconFileNames:(id)arg1;
- (void)setBoundIconCacheKey:(id)arg1;
- (void)setBoundIconsDictionary:(id)arg1;
- (void)setBoundResourcesDirectoryURL:(id)arg1;
- (void)setBoundDataContainerURL:(id)arg1;
- (void)setBoundContainerURL:(id)arg1;
- (void)setBoundApplicationIdentifier:(id)arg1;
- (id)localizedName;
- (void)dealloc;
- (id)iconDataForStyle:(id)arg1 width:(long long)arg2 height:(long long)arg3 options:(unsigned long long)arg4;


@end
